language: android
sudo: required
env:
  global:
    - ADB_INSTALL_TIMEOUT=15 # 8 minutes (2 minutes by default)

jdk:
  - oraclejdk8

cache:
  directories:

    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # python
    - $HOME/.cache/pip/

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - android-22
    - extra-google-google_play_services
    - extra-android-support
    - extra

before_install:
  - sudo pip install Pillow
  - yes | sdkmanager tools
  - yes | sdkmanager --licenses
  - sdkmanager 'system-images;android-22;default;armeabi-v7a'

before_script:
  - echo no | avdmanager create avd --force -n testCompactCalendarEmulator -k "system-images;android-22;default;armeabi-v7a"
  - mksdcard -l sdcard 100M sdcard
  - $ANDROID_HOME/emulator/emulator -avd testCompactCalendarEmulator -no-audio -no-window -sdcard sdcard &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew verifyMode screenshotTests -Pcom.android.build.threadPoolSize=1 -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xms1024m -Xmx1024m" -Dorg.gradle.daemon=true
  - ./gradlew test

